#!/bin/bash

numlockx on &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#xfce4-power-manager &
nm-applet &
/usr/lib/kdeconnectd &
kdeconnect-indicator &
nextcloud --background &
trash-empty 30 &
unclutter &
greenclip daemon &
mailspring -b &

sleep 2

blueman-applet &
pa-applet &
