#!/bin/bash

nitrogen --restore &
sh -c '~/.scripts/notifications' &
sh -c '~/.scripts/picom.sh' &
sh -c '~/.scripts/xob/start.sh' &
autotiling &
sh -c '~/.scripts/wacom' &
setxkbmap -option caps:escape &
sh -c 'find ~/.config/mpv/watch_later -mtime +30 -print | xargs rm -f' &
