#!/bin/sh

# QT
export QT_QPA_PLATFORMTHEME="gtk2"
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

sleep 2

autotiling &

xfce4-power-manager &

# Volume
volumeicon &

# Wifi & ethernet
nm-applet --indicator &

# Bleutooth
blueberry-tray &

# Nightmode
redshift-gtk &

# KDE Connect
/usr/lib/kdeconnectd &
sleep 1
kdeconnect-indicator &

# Nextcloud
owncloud &

# Empty trash
trash-empty 30
