#!/bin/bash

status=$(rofi-bluetooth --status | awk '{print $1}')
device=$(rofi-bluetooth --status | grep "WH-1000XM3")

if [ "$status" == "" ]  && [ -n "$device" ];
then
    if [ "$1" == "wayland" ];
    then
        echo "<span color='#5e81ac'></span>"
    elif [ "$1" == "clean" ];
    then
        echo ""
    else
        echo "%{F#5e81ac}"
    fi
else
    if [ "$1" == "wayland" ];
    then
        echo "<span color='#8fbcbb'>$status</span>"
    elif [ "$1" == "clean" ];
    then
        echo "$status"
    else
        echo "%{F#8fbcbb}$status"
    fi
fi
