#!/bin/sh

if [ -z "$2" ]; then
    echo "importpdf [file] [notebook]"
    exit
fi

# Generate markdown file from pdf
file="$(pwd)/$(~/.scripts/pdf2md $1)"
dir="$(echo "$file" | cut -f1 -d'.')"

echo $file
echo $dir

# Import generated markdown files
joplin import --format md $file $2
# Sync the client
joplin sync

rm -i $file
rm -ri $dir
