#!/bin/sh

count="$(xrandr | grep -w connected | wc -l)"

export GIFENABLED="false"

if [ "$count" == "3" ]; then
    xrandr --output DP1 --pos 0x0 --mode 1920x1080
    xrandr --output DP3 --pos 1920x0 --mode 2560x1440 --primary
    xrandr --output eDP1 --pos 4480x720 --mode 1920x1080
elif [ "$count" == "1" ]; then
    xrandr --output eDP1 --pos 0x0 --primary
    xrandr --output DP1 --off
    xrandr --output DP3 --off

    export GIFENABLED="true"
else
    xrandr --output eDP1 --pos 0x0 --primary
fi
