#!/bin/zsh

_trap_exit() 
{
    tmux kill-session -t $$;
}

trap _trap_exit EXIT QUIT INT 30


if [ -z "$1" ]; then
    alacritty -e env TERM=screen-256color tmux -2 new-session -s $$
elif [ "$2" = "--keep" ]; then
    name="$(echo $1 | cut -f1 -d' ')"
    env TERM=screen-256color tmux -2 new-session -d -s $$ -n $name
    env TERM=screen-256color tmux -2 send-keys -t $$:$name "$1 && clear && clear" Enter
    alacritty -e env TERM=screen-256color tmux attach -t $$:$name
else
    name="$(echo $1 | cut -f1 -d' ')"
    env TERM=screen-256color tmux -2 new-session -d -s $$ -n $name
    env TERM=screen-256color tmux -2 send-keys -t $$:$name "$1 && clear && tmux kill-session -t $$" Enter
    alacritty -e env TERM=screen-256color tmux attach -t $$:$name
fi
