#!/bin/sh

if [ -z "$1" ]; then
    ascii="/home/watcherwhale/.local/share/fish-ascii/$(ls ~/.local/share/fish-ascii | sort -R | tail -1)"
else
    ascii="/home/watcherwhale/.local/share/fish-ascii/$1"
fi

echo -n -e "\e[0m\e[34m"
cat $ascii
echo -n -e "\e[0m"
