#!/usr/bin/env bash

if [ -z "$1" ]; then
    ascii="/home/watcherwhale/.local/share/fish-ascii/$(ls ~/.local/share/fish-ascii | sort -R | tail -1)"
else
    ascii="/home/watcherwhale/.local/share/fish-ascii/$1"
fi

echo -n -e "\e[0m\e[34m"
cat $ascii
echo -n -e "\e[0m"

task due.after:yesterday due.before:30d list 2> /dev/null
exit 0
