#!/bin/sh


ffmpeg -y -i "$1" -vf fps=15,scale=320:-1:flags=lanczos,palettegen palette.png
ffmpeg -y -i "$1" -i palette.png -filter_complex "fps=15,scale=400:-1:flags=lanczos[x];[x][1:v]paletteuse" "$2"
rm palette.png
