#!/bin/sh

stylus=$(xsetwacom --list devices | grep "type: STYLUS" | awk -F'id:' '{print $1}' | awk '{$1=$1};1' | awk -F'\n' '{ print "\""$1"\"" }')
pad=$(xsetwacom --list devices | grep "type: PAD" | awk -F'id:' '{print $1}' | awk '{$1=$1};1' | awk -F'\n' '{ print "\""$1"\"" }')
monitor=$(autorandr | grep -w "(current)\|(detected)" | cut -d' ' -f1)

# Map output
if [ "$monitor" == "dock" ];
then
    xsetwacom set "Wacom Intuos S Pen stylus" MapToOutput 2560x1440+1920+0
elif [ "$monitor" == "dual" ]
then
    xsetwacom set "Wacom Intuos S Pen stylus" MapToOutput 1920x1080+1920+0
elif [ "$monitor" == "dualv" ]
then
    xsetwacom set "Wacom Intuos S Pen stylus" MapToOutput 1920x1080+0+1080
else
    xsetwacom set "Wacom Intuos S Pen stylus" MapToOutput 1920x1080+0+0
fi

# Set button shortcuts
xsetwacom set "Wacom Intuos S Pad pad" Button 8 "key Delete"
xsetwacom set "Wacom Intuos S Pad pad" Button 1 "key ctrl" "key z"
xsetwacom set "Wacom Intuos S Pad pad" Button 2 "key ctrl" "key s"
xsetwacom set "Wacom Intuos S Pad pad" Button 3 "key Print"
